# Generated by Django 3.2.6 on 2021-08-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210817_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='card_set_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
