# Generated by Django 3.2.6 on 2021-08-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.card'),
        ),
    ]
